# This is a basic workflow to help you get started with Actions

name: ConFusion

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install node modules
        uses: actions/setup-node@v2
      
      - name: Install dependencies
        run: npm install
      
      - name: Building application
        run: npm run build
      
      - name: Installing surge
        run: npm install -g surge
      
      - name: Deploying application on surge
        run: surge ./build confusion-reactjs-442.surge.sh --token ${{ secrets.SURGE_TOKEN }}
